customer_api/urls.py
from django.contrib import admin
from django.urls import path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

from customer.views import stock_list, stock_parameterized_data, add_stock, process_stock_entry, display_stocks

schema_view = get_schema_view(
    openapi.Info(
        title="Stock API",
        default_version='v1', ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('stocks/', stock_list),
    path('stocks/v1.0/<int:pk>/', stock_parameterized_data),
    path('add/', add_stock, name='add_stock'),
    path('process-stock-entry/', process_stock_entry, name='process_stock_entry'),
    path('show/', display_stocks, name='show_stocks'),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

day6/djangoproject/ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from ecommapp import views,abstractview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home),
    path('index/', views.index),
    path('show', views.show),
    path('add', views.employee),
path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('fetch/<str:path>', views.fetchData),
path('load/<int:level>', abstractview.showForm),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

day6/djangoproject/ecommerce/ecommapp/models.py
from django.db import models
import xml.etree.ElementTree as etree
import json
from abc import ABCMeta, abstractmethod
# Create your models here.

#abstract factory

class VEmployee(metaclass=ABCMeta):
    @abstractmethod
    def payment(self):
        pass

#permanent employee Factory1
class PermanentEmployee(VEmployee):

    def __init__(self,level):
        self.level=level

    def payment(self):
        if self.level==1:
            return HLM()
        if self.level==2:
            return MLM()
        if self.level==3:
            return LLM()


#Contract Employee Factory 2
class ContractEmployee(VEmployee):
    def __init__(self,level):
        self.level=level

    def payment(self):
        if self.level==1:
            return WBC()
        if self.level==2:
            return SBC()

class HLM(models.Model):
    def __init__(self):
        pass


class MLM(models.Model):
    def __init__(self):
        pass

class LLM(models.Model):
    def __init__(self):
        pass


class WBC(models.Model):
    def __init__(self):
        pass

class SBC(models.Model):
    def __init__(self):
        pass


class Employee(models.Model):
    eid = models.CharField(max_length=20,default='0')
    ename = models.CharField(max_length=100,default=' ')
    eemail = models.EmailField(default='sample@gmail.com')
    econtact = models.CharField(max_length=15,default='0000')
    class Meta:
        db_table = "employee"

import logging
#singleton with meta data
class MetaSingleton(type):
    _instances = {}
    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(MetaSingleton, \
            cls).__call__(*args, **kwargs)
        return cls._instances[cls]
class Logger(metaclass=MetaSingleton):
    def writeToLog(self,message):
        #self.message=message
        logging.info(message)


#abstract
class FileFactory(metaclass=ABCMeta):
    @staticmethod
    def choose(urlpath):
        if urlpath == 'json':
            return JsonLoader("donut.json")
        if urlpath == 'xml':
            return XmlLoader('person.xml')
    @abstractmethod
    def parsed_data(self):
        pass

#factory pattern
class JsonLoader(FileFactory):

     def __init__(self,filepath):
         with open(filepath, mode='r', encoding='utf-8') as f:
             self.data = json.load(f)

     def parsed_data(self):
         list=[]
         for donut in self.data:
             list.append(donut['name'])
             list.append(donut['ppu'])
         return list


class XmlLoader(FileFactory):
    def __init__(self, filepath):
       self.tree = etree.parse(filepath)

    def parsed_data(self):
        liars = self.tree.findall(".//{}[{}='{}']".format('person',
                                                         'lastName', 'Liar'))
        list=[]
        for liar in liars:
            list.append(liar.find('firstName').text)
            list.append(liar.find('lastName').text)

        return list

day6/djangoproject/ecommerce/ecommapp/forms.py
from django import forms
from ecommapp.models import Employee,HLM,MLM,LLM
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"


class HLMForm(forms.ModelForm):
    class Meta:
        model = HLM
        fields = "__all__"

class MLMForm(forms.ModelForm):
    class Meta:
        model = MLM
        fields = "__all__"
class LLMForm(forms.ModelForm):
    class Meta:
        model = LLM
        fields = "__all__"

day6/djangoproject/ecommerce/ecommapp/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.views.decorators.http import require_http_methods
from django.template import loader
import datetime
import ecommapp.forms as employeemodule
from ecommapp.models import Employee,FileFactory
from django.shortcuts import render,redirect

def home(request):
    return HttpResponse("<h2>Hello, Welcome to Django!</h2>")

def index(request):
    template = loader.get_template('index.html')  # getting our template
    name = {
        'employee': 'Dinesh'
    }
    return HttpResponse(template.render(name))

# @require_http_methods(["GET"])
# def show(request):
#     return HttpResponse('<h1>This is Http GET request.</h1>')

def employee(request):
    if request.method == "POST":
        form = employeemodule.EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        employee = employeemodule.EmployeeForm()
        return render(request,"employee.html",{'form':employee})

def show(request):
    employees = Employee.objects.all()
    return render(request,"show.html",{'employees':employees})
def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request,'edit.html', {'employee':employee})
def update(request, id):
    employee = Employee.objects.get(id=id)
    form = employeemodule.EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'employee': employee})
def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")


def fetchData(request,path):
    _instance=FileFactory.choose(path)
    return HttpResponse(_instance.parsed_data())

day6/djangoproject/ecommerce/ecommapp/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
        <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
        <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
        <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
        <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

day6/djangoproject/ecommerce/ecommapp/templates/employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/add">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
      {{ form.eid }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
      {{ form.ename }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
      {{ form.eemail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Contact:</label>
    <div class="col-sm-4">
      {{ form.econtact }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

day6/djangoproject/ecommerce/ecommapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     {% load static %}
     <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
      <link href="{% static '/css/styles.css' %}" rel="stylesheet">
</head>
<body>
<h4>Welcome to Django</h4>
<h5>My Name is: {{employee}}</h5>
<img src="{% static './who-we-are.jpg' %}" alt="My image" height="300px" width="700px"/>
</body>
</html>

day6/djangoproject/ecommerce/ecommapp/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
     {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>Employee Contact</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.eid }}</td>
        <td>{{ employee.ename }}</td>
        <td>{{ employee.eemail }}</td>
        <td>{{ employee.econtact }}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/add" class="btn btn-primary">Add New Record</a></center>
</body>
</html>